server:
  port: 8082


spring:
  application:
    name: manage-web
  freemarker:
    cache: false
    content-type: text/html
    suffix: .yml
    charset: UTF-8

  main:
    allow-bean-definition-overriding: true




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

manage:
  page:
    size: 8

movieinfo:
  page:
    size: 2